# Generated by Django 5.1 on 2025-01-15 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
