# Generated by Django 5.1 on 2025-01-15 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0003_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='education_app.student'),
        ),
    ]
